name: azam_shoshin_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"
dependencies:
  bloc: ^8.1.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_rating_bar: ^4.0.1
  google_fonts: ^6.1.0
  intl: ^0.19.0
  material_design_icons_flutter: ^7.0.7296
  meta: ^1.10.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/dummy_details.json
    - assets/dummy_tasks.json
